<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NormaCase.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NormaCase.Domain/NormaCase.Domain.csproj" />
    <ProjectReference Include="../NormaCase.Knowledge/NormaCase.Knowledge.csproj" />
    <ProjectReference Include="../NormaCase.RuleEngine/NormaCase.RuleEngine.csproj" />
  </ItemGroup>
</Project>
