import {isLosslessNumber} from 'lossless-json';
import de from './de.json';
import type {Presentation} from './model';
import {displayDecimal,displayValue,type ConditionTrace,type RuleTrace,type OutputTrace} from './trace';
const ui=de.clinicalWorkspace,labels={...de,unrecorded:de.decisionTrace.unrecorded};
function leaves(condition:ConditionTrace):ConditionTrace[]{return condition.children.length?(condition.kind==='all'||condition.kind==='any'?condition.children.flatMap(leaves):[condition,...condition.children.flatMap(leaves)]):[condition];}
function comparator(kind:string){return ({number_gte:'≥',field_equals:'=',number_in_range:ui.inclusiveRange,requires_evidence:de.evidence} as Record<string,string>)[kind]??(de.decisionTrace.conditions as Record<string,string>)[kind]??de.decisionTrace.unrecorded;}
export function RecordedCriteria({rule,outputs,presentation}:{rule?:RuleTrace;outputs?:OutputTrace[];presentation?:Presentation}){
 if(!rule&&!outputs?.length)return null;
 const rows=[...(rule?[{label:de.decisionTrace.entry,condition:rule.condition,source:rule.source}]:[]),...(outputs??[]).map(o=>({label:presentation?.outputs?.[o.outputId]?.label??de.outputReference,condition:o.condition,source:o.source}))];
 return <details className="recorded-criteria"><summary>{de.clinicalWorkspace.criteriaComparison}</summary><p>{ui.version}: {rule?(isLosslessNumber(rule.ruleVersion)?rule.ruleVersion.value:String(rule.ruleVersion)):de.decisionTrace.unrecorded} · {de.rule}: {rule?.ruleId??de.decisionTrace.unrecorded}</p><table><thead><tr><th>{ui.criterion}</th><th>{ui.value}</th><th>{ui.operator}</th><th>{ui.limit}</th><th>{ui.result}</th><th>{ui.source}</th></tr></thead><tbody>{rows.flatMap((row,index)=>leaves(row.condition).map((c,i)=><tr key={index+'-'+i}><td>{row.label}<small>{c.field?presentation?.fields[c.field]:c.evidenceRequirementId?presentation?.evidence[c.evidenceRequirementId]:(de.decisionTrace.conditions as Record<string,string>)[c.kind]}</small></td><td>{c.numericExpression?displayValue(c.numericExpression.value,labels):c.actual?displayValue(c.actual,labels):c.evidenceStatus?({PRESENT:de.present,MISSING:de.missing,CONFLICTING:de.conflicting} as Record<string,string>)[c.evidenceStatus]:de.decisionTrace.unrecorded}</td><td>{comparator(c.kind)}</td><td>{c.expected?displayValue(c.expected,labels):c.minimum!=null||c.maximum!=null?displayDecimal(c.minimum,de.decisionTrace.unrecorded)+' – '+displayDecimal(c.maximum,de.decisionTrace.unrecorded):de.decisionTrace.unrecorded}</td><td>{(de.decisionTrace.results as Record<string,string>)[c.result]??de.unknown}</td><td>{row.source.title}<small>{row.source.version} · {row.source.sourceLocation}</small></td></tr>))}</tbody></table></details>;
}
