<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NormaCase.Persistence.PostgreSql</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NormaCase.Application/NormaCase.Application.csproj" />
    <ProjectReference Include="../NormaCase.Serialization/NormaCase.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
